"""Test that agents don't send double messages after __ANNOUNCE_CONFIG__."""

from problems.graph_coloring import GraphColoring
from agents.rule_based_cluster_agent import RuleBasedClusterAgent
from comm.llm_rb_comm_layer import LLMRBCommLayer
from comm.rb_protocol import parse_rb
from agents.base_agent import Message

# Simple 3-cluster graph similar to the actual setup
local_nodes = ['h1', 'h2', 'h3', 'h4', 'h5', 'a1', 'a2', 'a3', 'a4', 'a5', 'b1', 'b2']
edges = [
    # Human cluster
    ('h1', 'h2'), ('h2', 'h3'), ('h3', 'h4'), ('h4', 'h5'),
    # Agent1 cluster
    ('a1', 'a2'), ('a2', 'a3'), ('a3', 'a4'), ('a4', 'a5'),
    # Agent2 cluster
    ('b1', 'b2'),
    # Boundary edges
    ('h1', 'a1'), ('h4', 'a4'),
    ('h2', 'b2'), ('h5', 'b1')
]
domain = ['red', 'green', 'blue']

problem = GraphColoring(local_nodes, edges, domain)

owners = {
    'h1': 'Human', 'h2': 'Human', 'h3': 'Human', 'h4': 'Human', 'h5': 'Human',
    'a1': 'Agent1', 'a2': 'Agent1', 'a3': 'Agent1', 'a4': 'Agent1', 'a5': 'Agent1',
    'b1': 'Agent2', 'b2': 'Agent2'
}

comm = LLMRBCommLayer(manual=True)

# Create Agent2
agent2 = RuleBasedClusterAgent(
    name='Agent2',
    local_nodes=['b1', 'b2'],
    owners=owners,
    problem=problem,
    comm_layer=comm,
    algorithm='greedy',
    initial_assignments={'b1': 'red', 'b2': 'red'}
)

# Set neighbor assignments (Human's local_nodes)
agent2.neighbour_assignments = {'h2': 'blue', 'h5': 'green'}

print("="*70)
print("TESTING __ANNOUNCE_CONFIG__ DOUBLE MESSAGE BUG")
print("="*70)

# Track messages sent
messages_sent = []

# Override send to capture messages
original_send = agent2.send
def capture_send(recipient, msg):
    messages_sent.append((recipient, msg))
    print(f"\n[{agent2.name} -> {recipient}]")
    # Parse and display
    rb_move = parse_rb(msg)
    if rb_move:
        from comm.rb_protocol import pretty_rb
        print(f"  {pretty_rb(rb_move)}")
    original_send(recipient, msg)

agent2.send = capture_send

print("\nStarting in CONFIGURE phase")
print(f"Phase: {agent2.rb_phase}")

# Simulate receiving __ANNOUNCE_CONFIG__
print("\n" + "="*70)
print("Simulating Human sending __ANNOUNCE_CONFIG__")
print("="*70)

msg_count_before = len(messages_sent)
print(f"\nMessages sent before: {msg_count_before}")

# Deliver __ANNOUNCE_CONFIG__ message
config_msg = Message(
    sender="Human",
    recipient="Agent2",
    content="__ANNOUNCE_CONFIG__"
)
agent2.receive(config_msg)
print(f"Phase after receive: {agent2.rb_phase}")

msg_count_after_receive = len(messages_sent)
print(f"Messages sent after receive(): {msg_count_after_receive}")
print(f"Messages generated by receive(): {msg_count_after_receive - msg_count_before}")

# Now call step() like cluster_simulation.py does
print("\n" + "-"*70)
print("Calling step() like cluster_simulation.py does")
print("-"*70)
agent2.step()

msg_count_after_step = len(messages_sent)
print(f"\nMessages sent after step(): {msg_count_after_step}")
print(f"Messages generated by step(): {msg_count_after_step - msg_count_after_receive}")

# Check results
print("\n" + "="*70)
print("RESULTS")
print("="*70)
print(f"Total messages sent: {msg_count_after_step}")
print(f"  From receive(): {msg_count_after_receive - msg_count_before}")
print(f"  From step(): {msg_count_after_step - msg_count_after_receive}")

if msg_count_after_step == 1:
    print("\n[OK] SUCCESS: Only 1 message sent (receive() handled it, step() skipped)")
elif msg_count_after_step == 2:
    print("\n[FAIL] BUG: 2 messages sent (both receive() and step() generated messages)")
    print("This causes the double message bug in the UI!")
else:
    print(f"\n[UNEXPECTED] {msg_count_after_step} messages sent")

print("\n" + "="*70)
